### ISSUE TITLE
gradle pactPublish fails

### ISSUE THREAD

**Issue by carwinz** [DiUS/pact-jvm#307]
I think the fix for #291 may have broken the successful publish case:

```
Publishing service-another-service.json ... HTTP/1.1 201 Created
:pactPublish FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':pactPublish'.
> No signature of method: org.apache.http.message.BasicStatusLine.startsWith() is applicable for argument types: (java.lang.String) values: [FAILED!]
```

PactBrokerClient returns resp.statusLine (a BasicStatusLine) whereas the failure case returns a string

      response.success = { resp -> resp.statusLine }
      response.failure = { resp, json ->
        def error = json?.errors?.join(', ') ?: 'Unknown error'
        "FAILED! ${resp.statusLine.statusCode} ${resp.statusLine.reasonPhrase} - ${error}"
      }

Occuring in 3.2.11

**Comment by uglyog** [comment]
Oops ;-)

**Comment by uglyog** [comment]
I've released version 3.2.13 with this fix

**Comment by carwinz** [comment]
Works now. Thanks @uglyog

**Comment by rcaval** [comment]
The recently published version 2.4.14 from (#310) has the same issue.

**Comment by uglyog** [comment]
I've released 2.4.15 with the fix

**Comment by rcaval** [comment]
the jar is still missing in https://mvnrepository.com/artifact/au.com.dius/pact-jvm-consumer-junit_2.11, is it expected?

**Comment by uglyog** [comment]
It can take a while for the index to propagate. search.maven.org is listing it: http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22au.com.dius%22%20AND%20a%3A%22pact-jvm-consumer-junit_2.11%22
