### ISSUE TITLE
pact-jvm-provider_2.11:3.4.0 - java.lang.NoSuchMethodError: groovy.lang.MetaClassImpl.hasCustomInvokeMethod()Z

### ISSUE THREAD

**Issue by shashidesai** [DiUS/pact-jvm#452]
Error seen with stacktrace:

> * Exception is:
> java.lang.NoSuchMethodError: groovy.lang.MetaClassImpl.hasCustomInvokeMethod()Z
> 	at au.com.dius.pact.provider.gradle.PactPlugin.apply(PactPlugin.groovy:20)
> 	at au.com.dius.pact.provider.gradle.PactPlugin.apply(PactPlugin.groovy)
> 	at org.gradle.api.internal.plugins.DefaultPluginContainer.providePlugin(DefaultPluginContainer.java:188)
> 	at org.gradle.api.internal.plugins.DefaultPluginContainer.addPluginInternal(DefaultPluginContainer.java:137)
> 	at org.gradle.api.internal.plugins.DefaultPluginContainer.apply(DefaultPluginContainer.java:103)
> 	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator$4.run(DefaultPluginRequestApplicator.java:128)
> 	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugin(DefaultPluginRequestApplicator.java:150)
> 	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugins(DefaultPluginRequestApplicator.java:126)
> 	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:168)
> 	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:39)
> 	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:26)
> 	at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
> 	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:55)
> 	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:521)
> 	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:82)
> 	at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:31)
> 	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:129)
> 	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
> 	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
> 	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
> 	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
> 	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
> 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
> 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
> 	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
> 	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:171)
> 	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
> 	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
> 	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
> 	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
> 	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
> 	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
> 	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
> 	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
> 	at org.gradle.launcher.Main.doAction(Main.java:33)
> 	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
> 	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
> 	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
> 	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
> 	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:31)
> 	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:108)
> 	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
> 
============================================================

> `$ gradle -version
> 
> Gradle 3.5
> 
> Build time:   2017-04-10 13:37:25 UTC
> Revision:     b762622a185d59ce0cfc9cbc6ab5dd22469e18a6
> 
> Groovy:       2.4.10
> Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
> JVM:          1.8.0_77 (Oracle Corporation 25.77-b03)
> OS:           Mac OS X 10.12.4 x86_64`

============================================================
**provider/build.gradle**  

```
plugins {
    id "au.com.dius.pact" version "3.4.0"
}

ext {
    PACT_DIR = "../pacts"
}

pact {

    publish {
        pactDirectory = PACT_DIR
        pactBrokerUrl = 'http://pact-broker'
        version = '0.1'
    }

    serviceProviders {
        provider {
            protocol ='http'
            host = 'provider1.com'
            port = 80
        
            hasPactWith("consumer-1") {
                pactFile = file("../pacts/consumer-1-provider-1.json")
            }
        }
    }
}

task wrapper(type: Wrapper) {
    gradleVersion = '3.5'
}
```

**Comment by uglyog** [comment]
I've released 3.4.1 and 3.5.0-rc.2 with updated Gradle and Groovy versions.

**Comment by shashidesai** [comment]
The provider/build.gradle is exactly as shown in the first comment.

Tried with 34.1 and I still see this error:
```
groovy.lang.MetaClassImpl.hasCustomInvokeMethod()Z
```

And with 3.5.0-rc.2 there is a different issue:
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'provider'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not find au.com.dius:pact-jvm-provider_2.11:3.5.0-rc.2.
     Searched in the following locations:
         https://plugins.gradle.org/m2/au/com/dius/pact-jvm-provider_2.11/3.5.0-rc.2/pact-jvm-provider_2.11-3.5.0-rc.2.pom
         https://plugins.gradle.org/m2/au/com/dius/pact-jvm-provider_2.11/3.5.0-rc.2/pact-jvm-provider_2.11-3.5.0-rc.2.jar
     Required by:
         :provider:unspecified > gradle.plugin.au.com.dius:pact-jvm-provider-gradle_2.11:3.5.0-rc.2
```

**Comment by uglyog** [comment]
Could you provide the contents of your project `gradle/wrapper/gradle-wrapper.properties` file?

**Comment by shashidesai** [comment]
I removed gradle wrapper and installed it again , so the properties file content.
And I don't see the `hasCustomInvokeMethod` error anymore.

Contents of `gradle/wrapper/gradle-wrapper.properties`
```
#Sun Jun 11 18:18:36 PDT 2017
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-3.5-bin.zip
```

**This is a new issue:**

I don't have provider tests, I just run pactVerify step. I am not sure if I am doing it right.

when the provider gradle file content is like the old format, the pactVerify step works fine.
```
apply plugin: 'java'
apply plugin: 'idea'
apply plugin: 'au.com.dius.pact'

buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath("au.com.dius:pact-jvm-provider-gradle_2.11:3.4.1")
    }
}

dependencies {
    testCompile("junit:junit")
    testCompile("au.com.dius:pact-jvm-provider_2.11:3.4.1")
}
```

but if I replace the above as per gradle - https://plugins.gradle.org/plugin/au.com.dius.pact/3.4.1
```
plugins {
  id "au.com.dius.pact" version "3.4.1"
}
```
I see an error:
```
Could not determine the dependencies of task ':pactVerify_flexinventory'.
> Task with path 'testClasses' not found in root project 'provider'.
```

**Comment by uglyog** [comment]
Could you rerun it with `-s` and provide the stack trace?

**Comment by shashidesai** [comment]
```
* What went wrong:
Could not determine the dependencies of task ':pactVerify_provider1'.
> Task with path 'testClasses' not found in root project 'provider'.

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.GradleException: Could not determine the dependencies of task ':pactVerify_provider1'.
        at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext.resolve(CachingTaskDependencyResolveContext.java:67)
        at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext.getDependencies(CachingTaskDependencyResolveContext.java:55)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.addToTaskGraph(DefaultTaskExecutionPlan.java:139)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.addTasks(DefaultTaskGraphExecuter.java:101)
        at org.gradle.execution.TaskNameResolvingBuildConfigurationAction.configure(TaskNameResolvingBuildConfigurationAction.java:47)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configure(DefaultBuildConfigurationActionExecuter.java:48)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.access$000(DefaultBuildConfigurationActionExecuter.java:25)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter$1.proceed(DefaultBuildConfigurationActionExecuter.java:54)
        at org.gradle.execution.DefaultTasksBuildExecutionAction.configure(DefaultTasksBuildExecutionAction.java:44)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configure(DefaultBuildConfigurationActionExecuter.java:48)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.access$000(DefaultBuildConfigurationActionExecuter.java:25)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter$1.proceed(DefaultBuildConfigurationActionExecuter.java:54)
        at org.gradle.execution.ExcludedTaskFilteringBuildConfigurationAction.configure(ExcludedTaskFilteringBuildConfigurationAction.java:47)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configure(DefaultBuildConfigurationActionExecuter.java:48)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.select(DefaultBuildConfigurationActionExecuter.java:36)
        at org.gradle.initialization.DefaultGradleLauncher$CalculateTaskGraphAction.execute(DefaultGradleLauncher.java:220)
        at org.gradle.initialization.DefaultGradleLauncher$CalculateTaskGraphAction.execute(DefaultGradleLauncher.java:217)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:158)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:112)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:95)
        at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:66)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:49)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:31)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
Caused by: org.gradle.api.UnknownTaskException: Task with path 'testClasses' not found in root project 'provider'.
        at org.gradle.api.internal.tasks.DefaultTaskContainer.getByPath(DefaultTaskContainer.java:190)
        at org.gradle.api.internal.tasks.DefaultTaskContainer.resolveTask(DefaultTaskContainer.java:172)
        at org.gradle.api.internal.tasks.DefaultTaskDependency.visitDependencies(DefaultTaskDependency.java:108)
        at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext$TaskGraphImpl.getNodeValues(CachingTaskDependencyResolveContext.java:88)
        at org.gradle.internal.graph.CachingDirectedGraphWalker$GraphWithEmpyEdges.getNodeValues(CachingDirectedGraphWalker.java:202)
        at org.gradle.internal.graph.CachingDirectedGraphWalker.doSearch(CachingDirectedGraphWalker.java:112)
        at org.gradle.internal.graph.CachingDirectedGraphWalker.findValues(CachingDirectedGraphWalker.java:64)
        at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext.doResolve(CachingTaskDependencyResolveContext.java:76)
        at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext.resolve(CachingTaskDependencyResolveContext.java:65)
        ... 57 more


BUILD FAILED

Total time: 0.937 secs
```

**Comment by shashidesai** [comment]
moving it to a different issue as the original is resolved.

**Comment by shashidesai** [comment]
https://github.com/DiUS/pact-jvm/issues/460
