### ISSUE TITLE
[pact-jvm-provider-gradle] Paths containing url encoded text cannot be verified

### ISSUE THREAD

**Issue by chrisholmes** [DiUS/pact-jvm#66]
When a path in the generated json pact file contains some already url encoded text (e.g. `xx%20xx -> xx%2520xx`), it is url encoded again after it is read in for use by `gradle pactVerify` which results in the verification failing.

This does not occur when the same generated json file is run using [pact-provider-proxy](https://github.com/bethesque/pact-provider-proxy).

**Comment by bethesque** [comment]
Does Netty still have this "problem"?

**Comment by uglyog** [comment]
No idea, but my assumption would be that it would.

**Comment by JimmyLv** [comment]
@uglyog Hi, But I want "+" symbol in path, because I want pass a datetime string in url like this "xxxx/xxx?datetime=2011-12-03T10:15:30+01:00", how can I fix it?

**Comment by uglyog** [comment]
Is this an issue you currently have? Query parameters with a `+` should work.

**Comment by JimmyLv** [comment]
@uglyog like this in my pact json file:

```json
"request": "GET",
"path": "/api/xxx/xxx",
"headers": {
},
"query": "datetime=2011-12-03T10:15:30+01:00"
```

and will send to my provider service(using SpringBoot), then actually I will get "`2011-12-03T10:15:30 01:00`" ("`+`" lost) when I map it from requestDTO, so that it will throw invalidation exception due to my `@DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME)` annotation.

**Comment by uglyog** [comment]
Ok, looks like the `+` is being incorrectly replaced with a space. I will try and find a fix for you.

If you are able, `%2B` is the encoded value for a `+`, so if you can use that it may work.

**Comment by JimmyLv** [comment]
@uglyog Thanks, but I have try to replace it with `%2B` alone, and it will still be distinguished as `%2B` string in my service. What I mean is just like this error msg: `Invalid format: "2015-08-20T10:15:30%2B01:00" is malformed at "%2B01:00"`

**Comment by JimmyLv** [comment]
@uglyog wait for your reply, T^T

**Comment by uglyog** [comment]
There is a change to the Pact specification to store the query strings in a different form, which will have to be implemented before I can resolve this issue. It will take a bit of work to fix.

**Comment by JimmyLv** [comment]
@uglyog Thank you, I has changed it to using '2011-12-03T10:15:30Z' datetime format and it works now.

**Comment by uglyog** [comment]
Version 3.1.0 allows V3 format pact files which should resolve this issue.

**Comment by nikhilkr123** [comment]
I am still facing similar issue.

My url is like this "_http://host/tenant/user%2Ftoken/issues_" but when its getting executed at provider side, I am getting 404 as request sending to the service is _http://host/tenant/user/token/issues_

I am using following version of lib.
`<dependency>
            <groupId>au.com.dius</groupId>
            <artifactId>pact-jvm-provider-junit_2.11</artifactId>
            <version>3.3.1</version>
</dependency>'

**Comment by nikhilkr123** [comment]
@uglyog 
I am still facing this problem with 3.3.1.
%2F in my URL path is getting converted into / at provider side.
I am using pact version 3.0.0
